const key='obavia-landing-preview-v1';
const defaults={step:0,company:'',role:'rep',focus:'babe'};
let state={...defaults}, writable=true;
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved&&typeof saved.company==='string'&&['rep','owner'].includes(saved.role)&&['babe','profit','business'].includes(saved.focus)&&Number.isInteger(saved.step)&&saved.step>=0&&saved.step<=2)state={step:saved.step,company:saved.company.slice(0,80),role:saved.role,focus:saved.focus};}catch{writable=false;}
const $=s=>document.querySelector(s);const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){try{localStorage.setItem(key,JSON.stringify(state));writable=true;$('#save-status').textContent='✓ Saved In This Browser';}catch{writable=false;$('#save-status').textContent='Browser storage unavailable. You can continue; progress lasts for this page only.';}}
function render(focus=false){document.querySelectorAll('#setup-progress li').forEach((li,i)=>{if(i===state.step)li.setAttribute('aria-current','step');else li.removeAttribute('aria-current');});let content='';
if(state.step===0)content=`<p class="eyebrow">Step 1 Of 3</p><h2 id="step-title" tabindex="-1">Who Is This Preview For?</h2><p class="intro">Give your practice space a name. No account is created.</p><form id="context-form"><label for="company">Team Name <span>(Optional)</span></label><input id="company" name="company" type="text" maxlength="80" autocomplete="organization" placeholder="Your Team" value="${esc(state.company)}"><div class="setup-actions"><button class="primary" type="submit">Continue <span aria-hidden="true"><svg class="control-chevron" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M9 5l7 7-7 7"/></svg></span></button></div></form>`;
if(state.step===1)content=`<p class="eyebrow">Step 2 Of 3</p><h2 id="step-title" tabindex="-1">What Do You Want To Notice?</h2><p class="intro">Choose the fictional conversation you’ll explore first.</p><form id="focus-form"><fieldset><legend>Conversation Focus</legend>${[['babe','Specific References','Why Babe Ruth, instead of someone else?'],['profit','Repeated Priorities','Profit keeps coming up.'],['business','Their Own Vocabulary','Keep industry and its meaning in the next question.']].map(([value,title,subtitle])=>`<label class="option"><input type="radio" name="focus" value="${value}" ${state.focus===value?'checked':''}><span><strong>${title}</strong><small>${subtitle}</small></span></label>`).join('')}</fieldset><div class="setup-actions"><button class="back" type="button" data-back>Back</button><button class="primary" type="submit">Continue <span aria-hidden="true"><svg class="control-chevron" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M9 5l7 7-7 7"/></svg></span></button></div></form>`;
if(state.step===2)content=`<p class="eyebrow">Step 3 Of 3</p><h2 id="step-title" tabindex="-1">Your Source Is Ready.</h2><p class="intro">${esc(state.company||'Your Team')} starts with a practice conversation.</p><div class="source-state"><span aria-hidden="true">✓</span><div><strong>Practice Conversation · Ready</strong><p>Explore the conversation and choose your next question.</p></div></div><div class="source-state"><span aria-hidden="true">○</span><div><strong>Live Calls & CRM · Not Connected</strong><p>Live connections are planned and unavailable in this preview.</p></div></div><div class="setup-actions"><button class="back" type="button" data-back>Back</button><a class="primary" href="./?example=${state.focus}#listener">Open Your Preview <span aria-hidden="true"><svg class="control-chevron" viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M9 5l7 7-7 7"/></svg></span></a></div>`;
$('#step-content').innerHTML=content;if(focus)$('#step-title').focus();if(!writable)$('#save-status').textContent='Browser storage unavailable. You can continue without saved progress.';
}
$('#step-content').addEventListener('input',event=>{const field=event.target;if(field.name==='company')state.company=field.value.slice(0,80);if(field.name==='role'&&['rep','owner'].includes(field.value))state.role=field.value;if(field.name==='focus'&&['babe','profit','business'].includes(field.value))state.focus=field.value;save();});
$('#step-content').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.target);if(state.step===0){state.company=String(form.get('company')||'').trim().slice(0,80);state.role=form.get('role')==='owner'?'owner':'rep';}else if(state.step===1){state.focus=String(form.get('focus'));}state.step=Math.min(2,state.step+1);render(true);save();});
$('#step-content').addEventListener('click',event=>{if(event.target.closest('[data-back]')){state.step=Math.max(0,state.step-1);render(true);save();}});
$('#reset').addEventListener('click',()=>{state={...defaults};render(true);save();$('#save-status').textContent=writable?'Preview Setup Reset. Saved In This Browser.':'Preview reset for this page. Browser storage unavailable.';});
render();
